const palette=[
{name:'Black',hex:'#151515'},{name:'White',hex:'#f0f0ec'},{name:'Charcoal',hex:'#484c51'},{name:'Grey',hex:'#747a80'},
{name:'Navy',hex:'#16263f'},{name:'Royal Blue',hex:'#1d5ea8'},{name:'Sky Blue',hex:'#6aaed6'},{name:'Red',hex:'#b91f2c'},
{name:'Maroon',hex:'#651e2c'},{name:'Orange',hex:'#d86a18'},{name:'Gold',hex:'#c89f27'},{name:'Bottle Green',hex:'#244b38'},
{name:'Olive',hex:'#66704c'},{name:'Khaki',hex:'#9a8b63'},{name:'Tan',hex:'#b29267'},{name:'Pink',hex:'#d783a4'}
];
const combos=[
{name:'Black / White',front:'#151515',mesh:'#f0f0ec',peak:'#151515',under:'#151515',button:'#151515',snap:'#151515',stitch:'#f0f0ec'},
{name:'Black / Gold',front:'#151515',mesh:'#151515',peak:'#c89f27',under:'#151515',button:'#c89f27',snap:'#151515',stitch:'#c89f27'},
{name:'Navy / White',front:'#16263f',mesh:'#f0f0ec',peak:'#16263f',under:'#16263f',button:'#16263f',snap:'#16263f',stitch:'#f0f0ec'},
{name:'Charcoal / Black',front:'#484c51',mesh:'#151515',peak:'#151515',under:'#151515',button:'#151515',snap:'#151515',stitch:'#f0f0ec'},
{name:'Khaki / Black',front:'#9a8b63',mesh:'#151515',peak:'#151515',under:'#151515',button:'#151515',snap:'#151515',stitch:'#f0f0ec'},
{name:'Olive / Black',front:'#66704c',mesh:'#151515',peak:'#151515',under:'#151515',button:'#151515',snap:'#151515',stitch:'#f0f0ec'},
{name:'Tan / Black',front:'#b29267',mesh:'#151515',peak:'#151515',under:'#151515',button:'#151515',snap:'#151515',stitch:'#f0f0ec'},
{name:'Pink / White',front:'#d783a4',mesh:'#f0f0ec',peak:'#d783a4',under:'#f0f0ec',button:'#d783a4',snap:'#f0f0ec',stitch:'#f0f0ec'},
{name:'Red / Black',front:'#b91f2c',mesh:'#151515',peak:'#151515',under:'#151515',button:'#151515',snap:'#151515',stitch:'#f0f0ec'},
{name:'Royal / White',front:'#1d5ea8',mesh:'#f0f0ec',peak:'#1d5ea8',under:'#1d5ea8',button:'#1d5ea8',snap:'#1d5ea8',stitch:'#f0f0ec'}
];
const defaults={style:'Classic Curved Peak',combo:'Black / White',front:'#151515',mesh:'#f0f0ec',peak:'#151515',under:'#151515',button:'#151515',stitch:'#f0f0ec',snap:'#151515',quantity:50,view:'front',logoName:'TC Coolers sample logo',frontText:'',frontTextColour:'#f0f0ec',frontTextSize:22,leftStripText:'',rightStripText:'',sideTextColour:'#f0f0ec',sideTextSize:17,rearPhone:'',rearPhoneColour:'#f0f0ec',rearPhoneSize:29,rearArch:'straight',showLogo:true};
const state={...defaults};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function colourName(hex){return palette.find(c=>c.hex.toLowerCase()===hex.toLowerCase())?.name||hex}
function contrast(hex){const n=parseInt(hex.slice(1),16),r=n>>16,g=n>>8&255,b=n&255;return (r*299+g*587+b*114)/1000>150?'#111':'#fff'}
function buildColourSelect(id,value){const el=$(id);palette.forEach(c=>{const o=document.createElement('option');o.value=c.hex;o.textContent=c.name;el.appendChild(o)});el.value=value}
function makeSwatches(){
  $$('.swatches').forEach(group=>{const part=group.dataset.part;palette.forEach(c=>{const b=document.createElement('button');b.type='button';b.className='swatch';b.title=c.name;b.style.background=c.hex;b.dataset.value=c.hex;if(c.hex===state[part])b.classList.add('active');b.addEventListener('click',()=>{state[part]=c.hex;state.combo='Custom';group.querySelectorAll('.swatch').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.combo').forEach(x=>x.classList.remove('active'));render()});group.appendChild(b)})})
}
function makeCombos(){const holder=$('#comboOptions');combos.forEach((c,i)=>{const b=document.createElement('button');b.type='button';b.className='combo'+(i===0?' active':'');b.innerHTML=`<i class="combo-cap" style="background:linear-gradient(90deg,${c.front} 0 56%,${c.mesh} 56%);--peak:${c.peak}"></i><span>${c.name}</span>`;b.addEventListener('click',()=>{Object.assign(state,c,{combo:c.name});$$('.combo').forEach(x=>x.classList.remove('active'));b.classList.add('active');syncSwatches();render()});holder.appendChild(b)})}
function syncSwatches(){$$('.swatches').forEach(group=>{const part=group.dataset.part;group.querySelectorAll('.swatch').forEach(b=>b.classList.toggle('active',b.dataset.value===state[part]))})}
function setFill(ids,value){ids.forEach(id=>$(id)?.setAttribute('fill',value))} function setStroke(ids,value){ids.forEach(id=>$(id)?.setAttribute('stroke',value))}
function render(){
  setFill(['#frontCrown','#sideCrown'],state.front);setFill(['#frontMesh','#sideMesh','#rearMesh'],state.mesh);setFill(['#frontPeak','#sidePeak'],state.peak);setFill(['#frontUnder','#sideUnder'],state.under);setFill(['#frontButton','#sideButton','#rearButton'],state.button);setFill(['#snapback'],state.snap);setFill(['#sideStrip','#rearStrip'],state.front);setStroke(['#frontStitches','#peakStitch','#sideStitches','#rearStitches'],state.stitch);
  const front=$('#frontTextPreview');front.textContent=state.frontText.toUpperCase();front.setAttribute('fill',state.frontTextColour);front.setAttribute('font-size',state.frontTextSize);
  $('#frontLogoGroup').classList.toggle('hidden',!state.showLogo);
  const left=$('#leftStripPreview');left.textContent=state.leftStripText.toUpperCase();left.setAttribute('fill',state.sideTextColour);left.setAttribute('font-size',state.sideTextSize);
  const right=$('#rightStripPreview');right.textContent=state.rightStripText.toUpperCase();right.setAttribute('fill',state.sideTextColour);right.setAttribute('font-size',state.sideTextSize);
  const straight=$('#rearPhoneStraight'),arched=$('#rearPhoneArched'),tp=arched.querySelector('textPath');straight.textContent=state.rearPhone.toUpperCase();straight.setAttribute('fill',state.rearPhoneColour);straight.setAttribute('font-size',state.rearPhoneSize);tp.textContent=state.rearPhone.toUpperCase();arched.setAttribute('fill',state.rearPhoneColour);arched.setAttribute('font-size',state.rearPhoneSize);straight.classList.toggle('hidden',state.rearArch!=='straight');arched.classList.toggle('hidden',state.rearArch!=='arched');
  ['front','side','rear'].forEach(v=>$(`#${v}View`).classList.toggle('hidden',state.view!==v));$$('.view-tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view));
  const locations=$$('.location:checked').map(x=>x.value).join(', ')||'None selected';
  $('#designSummary').innerHTML=`<div class="summary-item"><span>Style</span><strong>${state.style}</strong></div><div class="summary-item"><span>Combination</span><strong>${state.combo}</strong></div><div class="summary-item"><span>Front / Mesh</span><strong>${colourName(state.front)} / ${colourName(state.mesh)}</strong></div><div class="summary-item"><span>Peak / Under</span><strong>${colourName(state.peak)} / ${colourName(state.under)}</strong></div><div class="summary-item"><span>Rear phone</span><strong>${state.rearPhone||'None'}</strong></div><div class="summary-item"><span>Quantity</span><strong>${state.quantity}</strong></div>`;
  $('#designField').value=summaryText(locations)
}
function summaryText(locations=$$('.location:checked').map(x=>x.value).join(', ')||'None selected'){
return `CAP DESIGN SUMMARY\n\nCap profile: ${state.style}\nQuick combination: ${state.combo}\nQuantity: ${state.quantity}\n\nCOLOURS\nFront panels: ${colourName(state.front)}\nRear mesh: ${colourName(state.mesh)}\nPeak: ${colourName(state.peak)}\nUndervisor: ${colourName(state.under)}\nButton: ${colourName(state.button)}\nStitching: ${colourName(state.stitch)}\nSnapback: ${colourName(state.snap)}\n\nFRONT ARTWORK\nArtwork file: ${state.logoName}\nShow logo on preview: ${state.showLogo?'Yes':'No'}\nFront wording: ${state.frontText||'None'}\nFront wording colour: ${colourName(state.frontTextColour)}\n\nSIDE STRIPS\nLeft strip wording: ${state.leftStripText||'None'}\nRight strip wording: ${state.rightStripText||'None'}\nStrip wording colour: ${colourName(state.sideTextColour)}\n\nREAR MESH\nPhone number: ${state.rearPhone||'None'}\nPhone layout: ${state.rearArch==='arched'?'Arched':'Straight'}\nPhone colour: ${colourName(state.rearPhoneColour)}\n\nRequested embroidery locations: ${locations}`}
function bindText(id,key,upper=false){$(id).addEventListener('input',e=>{state[key]=upper?e.target.value.toUpperCase():e.target.value;render()})}
$$('#styleOptions .option').forEach(btn=>btn.addEventListener('click',()=>{$$('#styleOptions .option').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.style=btn.dataset.style;render()}));
$$('#quantityOptions button').forEach(btn=>btn.addEventListener('click',()=>{$$('#quantityOptions button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');state.quantity=btn.dataset.qty==='1000'?'1000+':Number(btn.dataset.qty);render()}));
$$('.view-tabs button').forEach(btn=>btn.addEventListener('click',()=>{state.view=btn.dataset.view;render()}));
$$('.location').forEach(c=>c.addEventListener('change',render));
bindText('#frontText','frontText',true);bindText('#leftStripText','leftStripText',true);bindText('#rightStripText','rightStripText',true);bindText('#rearPhone','rearPhone',true);
[['#frontTextSize','frontTextSize'],['#sideTextSize','sideTextSize'],['#rearPhoneSize','rearPhoneSize']].forEach(([id,key])=>$(id).addEventListener('input',e=>{state[key]=e.target.value;render()}));
[['#frontTextColour','frontTextColour'],['#sideTextColour','sideTextColour'],['#rearPhoneColour','rearPhoneColour'],['#rearArch','rearArch']].forEach(([id,key])=>$(id).addEventListener('change',e=>{state[key]=e.target.value;render()}));
$('#showLogo').addEventListener('change',e=>{state.showLogo=e.target.checked;render()});
$('#logoUpload').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;state.logoName=file.name;$('#fileName').textContent=file.name;if(file.type.startsWith('image/')){const reader=new FileReader();reader.onload=ev=>$('#logoImage').setAttribute('href',ev.target.result);reader.readAsDataURL(file)}render()});
$('#resetBtn').addEventListener('click',()=>{location.reload()});
$('#downloadBtn').addEventListener('click',()=>{const svg=$('#hatSvg'),clone=svg.cloneNode(true);clone.setAttribute('xmlns','http://www.w3.org/2000/svg');const blob=new Blob([new XMLSerializer().serializeToString(clone)],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const canvas=document.createElement('canvas');canvas.width=1520;canvas.height=1040;const ctx=canvas.getContext('2d');ctx.fillStyle='#202429';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);URL.revokeObjectURL(url);const a=document.createElement('a');a.download=`tc-coolers-${state.view}-cap-design.png`;a.href=canvas.toDataURL('image/png');a.click()};img.src=url});
$('#quoteForm').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,status=$('#formStatus');status.className='form-status';status.textContent='Sending your quote request…';$('#designField').value=summaryText();try{const data=new FormData(form);const res=await fetch('https://api.web3forms.com/submit',{method:'POST',body:data});const json=await res.json();if(!json.success)throw new Error(json.message||'Submission failed');status.className='form-status success';status.textContent='Thank you — your quote request has been sent directly to TC Coolers.';form.reset()}catch(err){status.className='form-status error';status.textContent='The form could not be sent. Please email tccoolers@gmail.com or try again.';console.error(err)}});
$('#year').textContent=new Date().getFullYear();buildColourSelect('#frontTextColour',state.frontTextColour);buildColourSelect('#sideTextColour',state.sideTextColour);buildColourSelect('#rearPhoneColour',state.rearPhoneColour);makeCombos();makeSwatches();render();
